### ISSUE TITLE
Support .github/release.yml

### ISSUE THREAD

**Issue by azu** [azu/github-label-setup#13]
[Automatically generated release notes - GitHub Docs](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) integration is useful.

Default preset is for github-label-setup.

**Comment by azu** [comment]
```yaml
changelog:
  exclude:
    labels:
      - 'Type: Meta'
      - 'Type: Question'

  categories:
    - title: Security Fixes
      labels: ['Type: Security']
    - title: Breaking Changes
      labels: ['Type: Breaking Change']
    - title: Features
      labels: ['Type: Feature']
    - title: Bug Fixes
      labels: ['Type: Bug']
    - title: Documentation
      labels: ['Type: Documentation']
    - title: Refactoring
      labels: ['Type: Refactoring']
    - title: Testing
      labels: ['Type: Testing']
    - title: Maintenance
      labels: ['Type: Maintenance']
    - title: CI
      labels: ['Type: CI']
    - title: Dependency Updates
      labels: ['Type: Dependencies', "dependencies"]
    - title: Other Changes
      labels: ['*']
```
